### ISSUE TITLE
provider download with s3 issue

### ISSUE THREAD

**Issue by AndriiOmelianenko** [outsideris/citizen#100]
so I have installed citizen in my k8s cluster, without s3 backend first (default).
works well, uploaded provider and downloaded it successfully.

then I've enabled s3 with:
```
          - name: CITIZEN_STORAGE
            value: s3
          - name: CITIZEN_AWS_S3_BUCKET
            value: my-bucket-for-citizen
```
uploaded the provider, it went well. I can see in S3 bucket my provider (it's around 5.2MB)
but when I try to download it as zip - it only gets me around 16KB of file, which is not full. it's still binary, so I could see portions of content there (like changelog.md filename)
```
�t�T
    	CHANGELOG.mdUT��kbRVV0�3�3P�+J�IM,NM���rrt�w
p                                                   r	V��s��
...
```

but it's not complete binary, so I couldn't use it. somehow the file gets stripped along the way (as on s3 it's still 5MB)

**Comment by outsideris** [comment]
fixed in #78
