### ISSUE TITLE
Don't require AWS ENV variables necessarily

### ISSUE THREAD

**Issue by richardgavel** [outsideris/citizen#31]
If the executable is running inside an AWS EC2 VM or a Docker container running in AWS Elasic Container Service, there should be no need to manually set the ACCESS_ID and SECRET_KEY as the code can access AWS resources under the IAM role assigned to it, making assigning one unnecessary.

**Comment by outsideris** [comment]
@richardgavel I got it what you mean. But doesn't it need IAM role, which has grant to access S3, for instance or ECS.

**Comment by robburger** [comment]
Hey @outsideris - we don't use any `AWS_ACCESS_KEY_ID` or `AWS_SECRET_ACCESS_KEY` for running our containers - only the IAM Role. The aws-sdk will handle searching for credentials in ENV or files or IAM Roles, so you don't need to check for them.

https://github.com/outsideris/citizen/pull/34 should solve that and output some additional info

**Comment by ludov04** [comment]
Same issue here, we don't use `AWS_ACCESS_KEY_ID `, handling the permissions through roles and instance profiles. 
The aws-sdk should handle that, no need to check for the variables

**Comment by ludov04** [comment]
Same issue here, we don't use `AWS_ACCESS_KEY_ID`, handling the necessary permissions via IAM Roles and instance profiles. 
Checking the existence of these variables renders this unusable for us.

Hopefully this PR gets merge soon!

**Comment by johnkeates** [comment]
Same here, we did some hacking on the code and it works, same result as the patch in the PR.
