### ISSUE TITLE
Switchable DB Backens: MongoDB

### ISSUE THREAD

**Issue by johnkeates** [outsideris/citizen#35]
I've been testing with citizen for a bit, and it looks very promising. We're having a bit of fun running it on Fargate, which has a downside: there is no persistent local storage, nor an option to mount a shared filesystem.

Since the internal storage API is relatively contained it should be possible to point to an external MongoDB or DocumentDB instance instead, which achieves persistence for stateless containers.

**Comment by outsideris** [comment]
I understand what you mean.
Currently db backend is not pluggable. I need to change it to support vary db backends.

**Comment by lifeofguenter** [comment]
maybe even an option for dynamodb because it would be much cheaper and easier to operate than documentdb?

or alternatively aurora serverless mysql/postgres? documentdb seems a bit heavy.

**Comment by johnkeates** [comment]
I came to the same conclusions after trying some things out in my fork; luckily, the module exports nice somewhat-universal-methods so it should be possible to put an RDBMS behind it.

With Dynamo, it would work on lighter loads, problem is that it is tricky to set the writer/reader units correctly when you use it for more than simple KV storage.

**Comment by outsideris** [comment]
Closed in #39
