### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by yves-vogl** [outsideris/citizen#48]
Hi @outsideris,

I hope you don't mind the question.

We were evaluating Terraform Private Registry solutions and found Citizen beside [Anthology](https://github.com/erikvanbrakel/anthology).

The latter one has not been updated since 3 years and is lacking a publish feature like you implemented, so we chose Citizen, which has a solid base. 

As there's no support for Terraform > 0.11 and the Docker images has not been patched since two years, we are now considering either to contribute to Citizen to try help solving these issues or to start a new project as we'd like to add more auxiliary services like a UI and authentication or even a feature to sell subscriptions to specific modules.

I'd love to hear from you - maybe we can team up.

Yves

**Comment by outsideris** [comment]
@yves-vogl 
Thank you for contacting me. I didn't deprecate Citizen, but I couldn't make time for Citizen after Terraform 0.11. Terraform 0.11 changed many things. 

The comments like you leave encourage me to put my effort into Citizen again. It will try to support Terraform 0.11+ soon. And contribution always welcome.!

**Comment by outsideris** [comment]
Recently I updated this project with Terraform latest versions, though it is not well tested yet.
