### ISSUE TITLE
Publishing Fails using s3 storage

### ISSUE THREAD

**Issue by mjdouble** [outsideris/citizen#57]
Hi there. I've been really digging your project. One issue I'm running into is I can't seem to publish when using s3 storage. Local file storage works fine, but I get a 500 error when I publish using s3 storage. Here is the error:

```
✔ compress the terraform module
✖ publish mjdouble/mj-mod/mjdouble/0.0.1
HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/snapshot/citizen/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: {
    start: 1616247957915,
    socket: 1616247957917,
    lookup: 1616247957917,
    connect: 1616247957918,
    secureConnect: undefined,
    upload: 1616247957919,
    response: 1616247957986,
    end: 1616247957987,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 0,
      tcp: 1,
      tls: undefined,
      request: 1,
      firstByte: 67,
      download: 1,
      total: 72
    }
  }
}
```

**Comment by outsideris** [comment]
I will check it. I tested this project in my local file system more than S3.

**Comment by outsideris** [comment]
@mjdouble It looks like citizen server doesn't have S3 permission. When I checked the S3 feature, it works. 
Can you show server logs?

**Comment by mjdouble** [comment]
Was your test with a local install or in AWS? the error i get locally is region is missing. It doesn't use AWS_DEFAULT_REGION. If running as a container in ECS it works. I thought it would work locally if the region was set in env along with the AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID

**Comment by mjdouble** [comment]
nevermind. I see you updated the documentation
