### ISSUE TITLE
Should allow module and provider names with multiple non-adjacent hyphens

### ISSUE THREAD

**Issue by sirlatrom** [outsideris/citizen#63]
Currently a module or provider name with multiple hyphens in its name will result in

> The name only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen.

However, the official Terraform Registry does allow multiple hyphens as long as they are non-adjacent.

**Comment by vaibhavkhurana2018** [comment]
Bumped into the same problem, went through the PR as well.  
+1 for getting this added. 

PS: There is a similar PR #69 which also allows underscores, although was not able to find any announcement regarding the use of underscores.

**Comment by outsideris** [comment]
Finxed in #83
