### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by AndriiOmelianenko** [outsideris/citizen#87]
Hi @outsideris!

Thank you for maintaining this project.

Would it make sense to create a new release from `main`, as the latest `0.4.0` is almost a year old and there have been many new things in `main` since then.

I'm the most interested in new docker image in Github Registry :)

**Comment by outsideris** [comment]
@AndriiOmelianenko Thank you for letting me know that.
I didn't forget to release it because I was busy last year. I will release it soon with the latest commit.

**Comment by AndriiOmelianenko** [comment]
hi, @outsideris thanks for the response. any plans to release it in the coming weeks?

**Comment by outsideris** [comment]
@AndriiOmelianenko I'm trying to address failed integration tests. So, I hope I can release new version in a couple of weeks.

**Comment by outsideris** [comment]
https://github.com/outsideris/citizen/releases/tag/v0.5.0

I released them. And I will check other issues soon.
